frr version 10.2.1
frr defaults traditional
hostname router8
agentx
!
interface eth1
 ip address 192.0.2.16/31
exit
!
interface eth2
 ip address 198.51.100.113/28
 ipv6 address 3fff:0:0:8::1/64
exit
!
interface lo
 ip address 192.0.2.200/32
 ipv6 address 3fff:203:0:113::39/128
exit
!
router bgp 65503
 bgp router-id 192.0.2.200
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 neighbor 192.0.2.17 remote-as 65502
 !
 address-family ipv4 unicast
  network 198.51.100.112/28
  neighbor 192.0.2.17 activate
  neighbor 192.0.2.17 soft-reconfiguration inbound
 exit-address-family
 !
 bmp targets clab-lab-01-minion-01
  bmp connect 203.0.113.64 port 11019 min-retry 100 max-retry 10000
 exit
exit
!
