---
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    jsonData:
      httpMethod: POST
      manageAlerts: false
      prometheusType: Mimir
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
  - name: ONMS Performance
    type: opennms-performance-datasource
    access: proxy
    database: ""
    orgId: 1
    url: http://onms-hzn-core:8980/opennms/
    isDefault: true
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin
  - name: ONMS Entity
    type: opennms-entity-datasource
    access: proxy
    database: ""
    orgId: 1
    url: http://onms-hzn-core:8980/opennms/
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin
  - name: OpenNMS Flow
    type: opennms-flow-datasource
    access: proxy
    database: ""
    orgId: 1
    url: http://onms-hzn-core:8980/opennms/
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin
  - name: postgres
    type: postgres
    access: proxy
    database: opennms
    url: database:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      postgresVersion: 1500
      sslmode: disable
      tlsAuth: false
      tlsSkipVerify: true
      timescaledb: true
