---
services:

  kafka-broker:
    image: quay.io/strimzi/kafka:latest-kafka-3.8.0
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 1g
    command:
      [
        "sh",
        "-c",
        "export CLUSTER_ID=$$(bin/kafka-storage.sh random-uuid) && bin/kafka-storage.sh format -t $$CLUSTER_ID -c config/kraft/server.properties && bin/kafka-server-start.sh config/kraft/server.properties --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} --override listeners=$${KAFKA_LISTENERS}",
      ]
    environment:
      TZ: UTC
      LOG_DIR: "/tmp/logs"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_HOST://localhost:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3 # The number of partitions > the number of Minions per Location, default is 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 20000
      KAFKA_LOG_SEGMENT_BYTES: 107374182
      KAFKA_LOG_SEGMENT_DELETE_DELAY_MS: 1000
    ports:
      - "9092/tcp"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      kafka-broker:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 512m
    environment:
      TZ: UTC
      KAFKA_CLUSTERS_0_NAME: onms-kafka-playground
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:9092
    ports:
      - "8080/tcp"
