---
services:

  kafka-broker:
    network_mode: host
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://localhost:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.10.45:9092,PLAINTEXT_HOST://localhost:29092

  kafka-ui:
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 192.168.10.45:9092
    ports:
      - "8080:8080/tcp"

  onms-hzn-core:
    depends_on:
      elasticsearch:
        condition: service_healthy
      mimir:
        condition: service_started
      kafka-broker:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      JAEGER_SERVICE_NAME: routing-lab-core
    volumes:
      - ./container-fs/core-etc-overlay:/opt/opennms-etc-overlay
      - ./container-fs/core-overlay:/opt/opennms-overlay
    ports:
      - "8101:8101/tcp"
      - "8980:8980/tcp"

  grafana:
    ports:
      - "3000:3000/tcp"

